"""The seeded story. Built at startup so the app never opens on an empty page.

Everything here comes off disk. No Vertex call runs during startup, deliberately:
the lab project is shared with every other team in the room and image generation
runs about 30 seconds a frame, so an app that needs the network to render its
first screen is an app that fails on stage.

Cards and frames already generated by the spike are reused from
`backend/demo_cache/`, which is why opening the app shows compiled Identity and
Voice Cards and a real board with real face scores before anyone touches Vertex.
"""
from __future__ import annotations

import json

from app.bible import index, reindex_story
from app.store import CACHE, SEED, Character, load_json, store

TITLE = "The Night Route"
LOGLINE = ("A depot dispatcher who controls everything learns the night route is "
           "being cut, and says nothing to the driver who has run it for "
           "twenty-two years.")

STYLE = {
    "medium": "photorealistic cinematic film still, 35mm",
    "palette": "sodium vapour orange against wet blue-black",
    "mood": "held breath, small rooms, fluorescent light",
    "era": "present day",
    "aspect": "2.39:1",
}

SCENES = [
    {"number": 1, "slugline": "INT. BUS DEPOT OFFICE - NIGHT", "int_ext": "INT",
     "time_of_day": "NIGHT",
     "synopsis": "Maya works the dispatch board alone. The route sheet for next "
                 "month is on her desk, and the night route is not on it.",
     "cast": ["Maya Raghavan"]},
    {"number": 2, "slugline": "EXT. DEPOT YARD - NIGHT", "int_ext": "EXT",
     "time_of_day": "NIGHT",
     "synopsis": "Rain. Ravi brings the last bus in and does his walk-around the "
                 "way he has done it for twenty-two years.",
     "cast": ["Ravi Menon"]},
    {"number": 3, "slugline": "INT. BUS DEPOT OFFICE - 4 AM", "int_ext": "INT",
     "time_of_day": "NIGHT",
     "synopsis": "Ravi comes in soaked, having found the notice himself. Maya "
                 "already knew. The scene is what she does not say.",
     "cast": ["Maya Raghavan", "Ravi Menon"]},
]

# The knowledge horizon, §6.4. Maya learns in scene 1 what Ravi does not learn
# until scene 3. This is the whole reason her scene 1 dialogue cannot reference
# his reaction and his scene 2 dialogue cannot reference the cut.
KNOWS = {
    "Maya Raghavan": [
        {"fact": "The night route is being cut at the end of the month.",
         "since_scene": 1},
        {"fact": "Ravi has run the night route for twenty-two years without an "
                 "accident.", "since_scene": 1},
        {"fact": "She was on shift and did not answer the phone the night her "
                 "mother died.", "since_scene": 1},
    ],
    "Ravi Menon": [
        {"fact": "He has run the night route for twenty-two years without an "
                 "accident.", "since_scene": 1},
        {"fact": "His wife packs him more food than he can eat.", "since_scene": 1},
        {"fact": "The night route is being cut at the end of the month.",
         "since_scene": 3},
    ],
}

# Real places, so Scout has something to show before the Places key is wired.
LOCATIONS = [
    {"name": "Jackie Gleason Bus Depot", "address": "861 Fifth Ave, Brooklyn, NY",
     "lat": 40.6528, "lng": -73.9962, "shortlisted": True,
     "notes": "Working MTA depot. Sodium light, wet concrete, real buses.",
     "maps_url": "https://www.google.com/maps/search/?api=1&query=40.6528,-73.9962"},
    {"name": "Kingsbridge Bus Depot", "address": "4650 Bailey Ave, Bronx, NY",
     "lat": 40.8790, "lng": -73.9010, "shortlisted": False,
     "notes": "Larger yard, better for the walk-around wide.",
     "maps_url": "https://www.google.com/maps/search/?api=1&query=40.8790,-73.9010"},
]

# Frames the spike already generated. Reused so the board is populated on open.
CACHED_SHOTS = [
    {"file": "maya_shot1.png", "description": "MAYA at the dispatch board, lit "
     "only by the monitor, reading the new route sheet.",
     "shot_size": "MCU", "angle": "eye", "lens": "50mm", "movement": "static"},
    {"file": "maya_shot2.png", "description": "MAYA seen through the office "
     "window from the wet yard outside, small inside the frame.",
     "shot_size": "WS", "angle": "eye", "lens": "35mm", "movement": "static"},
    {"file": "maya_shot3.png", "description": "MAYA's hands flattening the route "
     "sheet on the desk. She does not look at it.",
     "shot_size": "ECU", "angle": "high", "lens": "85mm", "movement": "static"},
    {"file": "maya_shot4.png", "description": "MAYA turning toward the door as "
     "headlights sweep the office wall.",
     "shot_size": "MS", "angle": "low", "lens": "35mm", "movement": "pan"},
]


def _answers_for(name: str, card: dict) -> dict[str, str]:
    """Back-fill the core interview answers implied by an already compiled card.

    The real flow is the opposite direction: answers are the source and the card
    is derived. Doing it backwards for the seed keeps the character builder tab
    the only writer of answers in the live app, while still letting the seeded
    story show a fully populated interview.
    """
    reg = card.get("register", {})
    a = {
        "What is your full name?": name,
        "What does your voice sound like?": card.get("card", ""),
        "What words and/or phrases do you use very frequently?":
            "; ".join(card.get("phrases", [])),
        "Do you have any quirks, strange mannerisms, annoying habits, or other "
        "defining characteristics?":
            f"Silence: {reg.get('silence','')}. Humour: {reg.get('humour','')}",
        "How honest are you about your thoughts and feelings (i.e. do you hide "
        "your true self from others, and in what way)?": reg.get("hedging", ""),
        "In general, how do you treat others (politely, rudely, by keeping them "
        "at a distance, etc.)? Does your treatment of them change depending on "
        "how well you know them, and if so, how?": reg.get("formality", ""),
    }
    if name.startswith("Maya"):
        a.update({
            "What do you consider the most important event of your life so far?":
                "I was on shift the night my mother died. I did not answer the "
                "phone. I have not been late for anything since.",
            "What is your greatest regret?": "Not answering the phone.",
            "What is your greatest fear?":
                "That being in control of everything is not the same as being "
                "able to stop anything.",
            "What is your greatest strength as a person?":
                "I do not panic and I do not need anyone to help me.",
            "What is your greatest weakness?": "The same sentence.",
            "What three words best describe your personality?":
                "Contained. Exact. Unreachable.",
        })
    else:
        a.update({
            "What do you consider the most important event of your life so far?":
                "Twenty-two years on the night route and not one accident. Ask "
                "anyone at the depot, they will tell you the same.",
            "What is your greatest regret?":
                "That my son does not want the job. It is a good job.",
            "What is your greatest fear?": "Sitting still.",
            "What is your greatest strength as a person?":
                "I talk to everyone, so everyone talks to me.",
            "What is your greatest weakness?":
                "I talk over people. My wife tells me. I am working on it.",
            "What three words best describe your personality?":
                "Warm. Loud. Loyal.",
        })
    return {k: v for k, v in a.items() if v}


def _cached(name: str) -> str | None:
    p = CACHE / name
    return f"/cache/{name}" if p.exists() else None


def build() -> str:
    """Build the seeded story. Returns its id."""
    st = store.create_story(TITLE, LOGLINE, style=STYLE, format="short")
    st.summary = ("Scene 1 establishes that Maya knows. Scene 2 establishes what "
                  "Ravi is about to lose. Scene 3 is the conversation where she "
                  "does not tell him.")

    cards: list[dict] = []
    dpath = CACHE / "dialogue.json"
    if dpath.exists():
        cards = load_json(dpath).get("cards", [])

    identity_by_name: dict[str, dict] = {}
    mcard = CACHE / "maya_card.json"
    if mcard.exists():
        c = load_json(mcard)
        identity_by_name[c["name"]] = c
    ex = SEED / "example_identity_card.json"
    if ex.exists():
        c = load_json(ex)
        identity_by_name.setdefault(c["name"], c)

    for vc in cards or [{"name": "Maya Raghavan"}, {"name": "Ravi Menon"}]:
        name = vc["name"]
        ch: Character = store.add_character(
            st.id, name,
            role="lead" if name.startswith("Maya") else "supporting",
            answers=_answers_for(name, vc),
            knows=KNOWS.get(name, []))
        ch.aliases = [name.split()[0]]
        if vc.get("card"):
            ch.voice_card = {k: vc.get(k) for k in
                             ("card", "register", "phrases", "never_says",
                              "samples")}
            ch.voice_card["canon_version"] = 1
        if name in identity_by_name:
            ic = identity_by_name[name]
            ch.identity_card = {"descriptor": ic["descriptor"],
                                "wardrobe": ic["wardrobe"],
                                "negative": ic.get("negative", ""),
                                "canon_version": 1}
            ch.sheet_url = _cached("maya_sheet.png") if name.startswith("Maya") \
                else None

    for l in LOCATIONS:
        loc = store.add_location(st.id, **l)
        if loc.shortlisted:
            for sc_num in (1, 3):
                pass  # attached below, once scenes exist

    for spec in SCENES:
        cast_ids = [c.id for c in st.characters.values()
                    if c.name in spec["cast"]]
        sc = store.add_scene(st.id, spec["number"], spec["slugline"],
                             synopsis=spec["synopsis"],
                             int_ext=spec["int_ext"],
                             time_of_day=spec["time_of_day"],
                             characters=cast_ids)
        # Continuity state, §6.2 step 4: the wet clothes in scene 3 are why the
        # frame can carry a state forward instead of resetting every shot.
        if spec["number"] == 3:
            ravi = st.character_by_name("Ravi Menon")
            if ravi:
                sc.continuity[ravi.id] = {
                    "wardrobe": "soaked navy MTA uniform shirt, sleeves rolled",
                    "physical": "hair flat with rain, water running off his cuffs",
                    "emotional": "still cheerful, has not understood yet"}
        first = next(iter(st.locations.values()), None)
        if first and spec["int_ext"] == "INT":
            sc.location_ids = [first.id]

    scene1 = st.scene_by_number(1)
    maya = st.character_by_name("Maya Raghavan")
    if scene1 and maya:
        for spec in CACHED_SHOTS:
            url = _cached(spec["file"])
            sh = store.add_shot(
                st.id, scene1.id, spec["description"],
                shot_size=spec["shot_size"], angle=spec["angle"],
                lens=spec["lens"], movement=spec["movement"],
                characters=[maya.id], subject="Maya")
            if url:
                sh.image_url = url
                sh.status = "ready"
                sh.attempts = 1
                # Scores measured by the spike on these exact frames. Kept rather
                # than invented, because a fabricated score on a demo screen is
                # the one number nobody would ever catch.
                sh.face_scores = {maya.id: None}

    store.default_story_id = st.id
    n = reindex_story(st.id)
    print(f"  seed: {TITLE} · {len(st.characters)} characters, "
          f"{len(st.scenes)} scenes, {len(st.locations)} locations, {n} chunks")
    return st.id
